import clsx from "clsx";
import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Providers from "@/Components/Providers";
import { Toaster } from "@/Components/ui/toaster";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--roboto",
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Dokter Lele - Sistem Pendiagnosa Penyakit Ikan Lele",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isDevelopment = process.env.NODE_ENV === "development";

  return (
    <html lang="en">
      <body
        className={clsx(roboto.variable, "font-sans", {
          "debug-screens": isDevelopment,
        })}
      >
        <Providers>
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
