import clsx from "clsx";
import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--roboto",
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isProduction = process.env.NODE_ENV;
  return (
    <html lang="en">
      <body
        className={clsx(roboto.variable, "font-sans", {
          "debug-screens": isProduction,
        })}
      >
        {children}
      </body>
    </html>
  );
}
